version: '3.9'

services:
  quizis-app-production:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    links:
      - mongo
  quizis-app-dev:
    build:
      context: .
      target: dev
      args:
        - PORT=${PORT}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    links:
      - mongo
    volumes:
      - .:/proyect
      - node_modules:/proyect/node_modules
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
  node_modules:
